apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  namespace: frontend   # 👈 IMPORTANT
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular-container
        image: daneshkabade45/ecomm_store:latest   # 👈 better for pipeline
        ports:
        - containerPort: 80
        imagePullPolicy: Always                    # 👈 ensure latest image
---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
  namespace: frontend   # 👈 IMPORTANT
spec:
  type: LoadBalancer
  selector:
    app: angular
  ports:
  - port: 80
    targetPort: 80
